mysql:
  host: 10.100.146.228
  port: 3306
  db: amplat
  user: amplat
  password: amplat  
  connect_timeout: 5000
  minsize: 1
  maxsize: 5
  
redis:
  host: 10.100.137.94
  port: 7000
  minsize: 1
  maxsize: 5 

host: 127.0.0.1
port: 8080