mysql:
  host: localhost
  port: 3306
  db: bus
  user: linqt
  password: 123qwe  
  connect_timeout: 5000
  minsize: 1
  maxsize: 5
  
redis:
  host: localhost
  port: 7000
  minsize: 1
  maxsize: 5 

host: 127.0.0.1
port: 8080